version: '3'
services:
  web:
      image: nginx:alpine
      ports:
          - "8080:80"
      volumes:
          - ./:/var/www/
          - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      depends_on:
          - php
  php:
      build: ./docker/php
      working_dir: /var/www
      volumes:
          - ./:/var/www/
      ports:
          - "9000:9000"
